Feature/arpa 232 new and changed properties
orso-co/Orso.Arpa.Api pull request #165
Opened 2021-04-25 19:38 UTC by euphi967

2021-04-26 16:03 UTC, VILLAN3LL3 requested changes

2021-04-26 16:03 UTC, VILLAN3LL3 commented on Orso.Arpa.Persistence/Configurations/MusicianProfileConfiguration.cs
> -            builder
Warum hast du das gelöscht?

2021-04-26 16:03 UTC, VILLAN3LL3 commented on Orso.Arpa.Persistence/DataAccess/ArpaContext.cs
> +        public DbSet<Reference> Credentials { get; set; }
Bitte den Property Wert an den Klassennamen angleichen

2021-04-26 16:51 UTC, euphi967 commented on Orso.Arpa.Domain/Entities/MusicianProfile.cs
> -        public virtual Position PreferredPosition { get; private set; }
ist jetzt PositionPreference, d.h. eine Collection

2021-04-26 17:08 UTC, euphi967 commented on Orso.Arpa.Domain/Entities/MusicianProfileReference.cs
> +    public class MusicianProfileReference : BaseEntity
hieß vorher Credential

2021-04-26 17:13 UTC, euphi967 commented on Orso.Arpa.Persistence/Configurations/MusicianProfileConfiguration.cs
> -            builder
ist umbenannt in InquiryStatusId

2021-04-26 19:36 UTC, VILLAN3LL3 commented on Orso.Arpa.Domain/Entities/MusicianProfileReference.cs
> +    public class MusicianProfileReference : BaseEntity
Wurde aus Credential nicht Reference?

2021-04-29 17:04 UTC, euphi967 commented on Orso.Arpa.Domain/Entities/MusicianProfileReference.cs
> +    public class MusicianProfileReference : BaseEntity
m:n

2021-04-29 17:05 UTC, euphi967 commented on Orso.Arpa.Domain/Entities/Reference.cs
> +    public class Reference : BaseEntity
wird noch in CurriculumVitaeReference geändert

2021-04-29 19:53 UTC, euphi967 commented on Orso.Arpa.Persistence/Configurations/CredentialConfiguration.cs
> +    public class CredentialConfiguration : IEntityTypeConfiguration<Reference>
done

2021-04-29 19:53 UTC, euphi967 commented on Orso.Arpa.Persistence/DataAccess/ArpaContext.cs
> +        public DbSet<Reference> Credentials { get; set; }
done

2021-04-30 16:29 UTC, closed without merging