Feature/arpa 313 collections
orso-co/Orso.Arpa.Api pull request #188
Opened 2021-05-27 18:10 UTC by VILLAN3LL3

- PreferredPositionsStaff
- PreferredPositionsPerformer
- DoublingInstruments
- PreferredPartsStaff
- PreferredPartsPerformer

2021-05-27 20:12 UTC, euphi967 requested changes

2021-05-28 09:00 UTC, VILLAN3LL3 commented on Orso.Arpa.Persistence/Seed/SectionSeedData.cs
> -        public static Section Flute => new(Guid.Parse("d6961f83-e792-4ddf-b91a-ae0867caeb3b"), "Flute", Woodwinds.Id, true);
Das ist für mich Out of Scope für diesen Pull Request. Außerdem möchte ich diese Anpassung ungern vor Dienstag reinbringen, weil da ggf. auch noch Datenbereinigungen auf der Testdatenbank erforderlich sein werden, wenn Sections gelöscht werden (bestehende Fremdverschlüsselungen). Gerne in einem separaten Branch, der dann erst nach Dienstag germergt wird.

2021-05-28 13:05 UTC, VILLAN3LL3 commented on Tests/Orso.Arpa.Tests.Shared/TestSeedData/MusicianProfileSeedData.cs
> +                    InstrumentId = SectionSeedData.BaritoneHorn.Id,
Changed to Wagner Tuba

2021-05-28 13:13 UTC, VILLAN3LL3 commented on Orso.Arpa.Persistence/Seed/SectionSeedData.cs
> -        public static Section Flute => new(Guid.Parse("d6961f83-e792-4ddf-b91a-ae0867caeb3b"), "Flute", Woodwinds.Id, true);
Zum Thena InstrumentPartCount: Meinem Gefühl nach verwendet man im Englischen hier das Singular (vergleichbare Beispiele: head count, activity count. Kann aber gern auch nochmal ein native speakter gegenchecken.

2021-05-28 15:08 UTC, merged