feature/arpa-366_completing_SelectValueSectionsSeedData
orso-co/Orso.Arpa.Api pull request #201
Opened 2021-06-03 16:11 UTC by wolfgangroese

2021-06-03 16:12 UTC, wolfgangroese commented
ui... gehört da auch dto-mässig was dazu, was ich nachziehen muss? zu spät eingefallen danach zu suchen 🙈 @VILLAN3LL3

2021-06-04 16:58 UTC, VILLAN3LL3 requested changes

2021-06-04 16:58 UTC, VILLAN3LL3 commented on Orso.Arpa.Persistence/Seed/SelectValueSectionSeedData.cs
> +        ublic static SelectValueSection TenorSectionLead => new(Guid.Parse("e0eadd53-5de4-4d3a-82ad-3551b9a22766"), SectionSeedData.Tenor.Id, SelectValueSeedData.SectionLead.Id);
Hier fehlt ein p :)

2021-06-04 18:37 UTC, wolfgangroese commented on Orso.Arpa.Persistence/Seed/SelectValueSectionSeedData.cs
> +        ublic static SelectValueSection TenorSectionLead => new(Guid.Parse("e0eadd53-5de4-4d3a-82ad-3551b9a22766"), SectionSeedData.Tenor.Id, SelectValueSeedData.SectionLead.Id);
uck..! 
:-D

2021-06-04 18:50 UTC, wolfgangroese commented on Orso.Arpa.Persistence/Seed/SelectValueSectionSeedData.cs
> +        ublic static SelectValueSection TenorSectionLead => new(Guid.Parse("e0eadd53-5de4-4d3a-82ad-3551b9a22766"), SectionSeedData.Tenor.Id, SelectValueSeedData.SectionLead.Id);
✔️

2021-06-08 17:13 UTC, VILLAN3LL3 commented
@wolfgangroese  ich fixe den branch

2021-06-08 17:44 UTC, VILLAN3LL3 approved these changes

2021-06-08 17:44 UTC, merged