Feature/arpa 329 mucianprofile documents
orso-co/Orso.Arpa.Api pull request #225
Opened 2021-07-13 20:52 UTC by VILLAN3LL3

2021-07-14 18:51 UTC, euphi967 requested changes
very minor finding, please fix typo

2021-07-14 18:51 UTC, euphi967 commented on Orso.Arpa.Api/Controllers/MyMusicianProfileDocumentsController.cs
> +            await _meService.AddDocumentToMusicienProfileAsync(addDocumentDto);
fix typo AddDocumentToMusicianProfileAsync

2021-07-15 15:00 UTC, VILLAN3LL3 commented on Orso.Arpa.Api/Controllers/MyMusicianProfileDocumentsController.cs
> +            await _meService.AddDocumentToMusicienProfileAsync(addDocumentDto);
fixed

2021-07-15 19:21 UTC, euphi967 approved these changes

2021-07-15 19:31 UTC, merged