Update Reset_Password.txt
orso-co/Orso.Arpa.Api pull request #73
Opened 2021-02-08 17:10 UTC by wolfgangroese

2021-02-08 17:12 UTC, wolfgangroese commented
2 Dinge sind mir nicht ganz klar: 

- Betreff-Zeile: Da steht jetzt auch einfach beides drin nehm ich an..? (weil wir ja gesagt haben beide Sprachen in einer Mail, untereinander. 
- Vorschau/Preview: same here.. habs jetzt auch quasi in eine Zeile "gequetscht" ,-) 

Schöner fände ich grundsätzlich schon, wenn's für jede Sprache doch ein eigenes Template da wäre (später irgendwann).  Oder gibts noch ne andere möglichkeit, "Subjekt" und "Preview" für die jeweilige sprache nur auszutauschen?

2021-02-09 07:02 UTC, VILLAN3LL3 requested changes

2021-02-09 07:02 UTC, VILLAN3LL3 commented on Orso.Arpa.Mail/Templates/Heml/Reset_Password.txt
> +          <h6><b>Adress:</b> {{ClubAddress}}</h6>
Address schreibt man im Englischen mit 2 d :)

2021-02-09 07:02 UTC, VILLAN3LL3 commented on Orso.Arpa.Mail/Templates/Heml/Reset_Password.txt
> +    <preview>Du hast uns mitgeteilt, dass du dein zurücksetzen möchtest./ You were asking for a password reset</preview>
Beim Subject hast du eine Pipe | verwendet für die Deutsch/Englisch-Trennung. Beim Preview aber ein Slash /. Wäre vielleicht einheitlich besser?

2021-02-09 07:05 UTC, VILLAN3LL3 requested changes
Nach den Korrekturen wirst du das HTML ha auch wieder austauschen müssen, daher approve ich das dann erst anschließend - wäre sinnvoller in einem gemeinsamen Pull Request

2021-02-09 07:05 UTC, VILLAN3LL3 commented on Orso.Arpa.Mail/Templates/Heml/Reset_Password.txt
> +    <preview>Du hast uns mitgeteilt, dass du dein zurücksetzen möchtest./ You were asking for a password reset</preview>
Beim preview fehlt das Wort "Passwort": "[...], dass du dein zurücksetzen möchtest"

2021-02-09 07:09 UTC, VILLAN3LL3 commented
> 
> 
> 2 Dinge sind mir nicht ganz klar:
> 
>     * Betreff-Zeile: Da steht jetzt auch einfach beides drin nehm ich an..? (weil wir ja gesagt haben beide Sprachen in einer Mail, untereinander.
> 
>     * Vorschau/Preview: same here.. habs jetzt auch quasi in eine Zeile "gequetscht" ,-)
> 
> 
> Schöner fände ich grundsätzlich schon, wenn's für jede Sprache doch ein eigenes Template da wäre (später irgendwann). Oder gibts noch ne andere möglichkeit, "Subjekt" und "Preview" für die jeweilige sprache nur auszutauschen?

Ich denke, es gibt keine saubere Möglichkeit, Subject und Preview hinterher auszutauschen. Die Idee ist ja auch, dass jeder Verein da seinen eigenen Text hinterlegen kann und da wäre es problematisch, wenn der Code hinterher anfangen würde, Texte auszutauschen. Außerdem sind die aus dem HTML nicht gut herauslösbar. Separate Templates wäre prinzipiell möglich, allerdings stellt sich hier die Frage, ob wir die gewünschte Sprache überhaupt in allen Fällen kennen, da teilweise ja auch Mails verschickt werden, ohne dass ein User eingeloggt ist (z. B. Passwort Reset). Die einfache und sichere Variante ist mit Sicherheit die zwei-Sprachen-in-einem-Template-Lösung. Zumindest solange wir nur zwei Sprachen unterstützen. Eventuell könnte man die Zweitsprache optisch noch etwas abheben, indem man sie beispielsweise etwas kleiner anzeigt oder auch kursiv.

2021-02-09 09:58 UTC, wolfgangroese reviewed
ich hoffe, ich hab alles richtig jetzt.. bin manchmal immer noch verwirrt wo ich was finde..  gar nicht einfach in all den änderungen und versionen noch durchzublicken.. 🙈😬

2021-02-09 09:59 UTC, wolfgangroese commented on Orso.Arpa.Mail/Templates/Heml/Reset_Password.txt
> +          <h6><b>Adress:</b> {{ClubAddress}}</h6>
ist korrigiert :-)

2021-02-09 09:59 UTC, wolfgangroese commented on Orso.Arpa.Mail/Templates/Heml/Reset_Password.txt
> +          <h3>Cheers! Your Arpa-Team of {ClubName}}</h3>
ist korrigiert :-)

2021-02-09 09:59 UTC, wolfgangroese commented on Orso.Arpa.Mail/Templates/Heml/Reset_Password.txt
> +          <h3>Das Arpa-Team von {ClubName}}</h3>
ist korrigiert :-)

2021-02-09 09:59 UTC, wolfgangroese commented on Orso.Arpa.Mail/Templates/Heml/Reset_Password.txt
> +    <preview>Du hast uns mitgeteilt, dass du dein zurücksetzen möchtest./ You were asking for a password reset</preview>
ist korrigiert :-)

2021-02-09 10:05 UTC, VILLAN3LL3 approved these changes

2021-02-10 20:47 UTC, VILLAN3LL3 commented
See PR #75

2021-02-10 20:47 UTC, closed without merging