new property "newsTitle" added
orso-co/Orso.Arpa.Api pull request #737
Opened 2023-06-22 14:17 UTC by wolfgangroese

2023-06-22 15:19 UTC, VILLAN3LL3 requested changes

2023-06-22 15:19 UTC, VILLAN3LL3 commented on Orso.Arpa.Application/NewsApplication/NewsCreateDto.cs
> +        public string NewsTitle { get; set; }
Ich frage mich, warum die Properties NewsTitle und NewsText heißen müssen. Da die Entity News ist, ist doch irgendwie logisch wohin Title und Text (Body?) gehört?

2023-06-22 15:19 UTC, VILLAN3LL3 commented on Orso.Arpa.Persistence/Migrations/20230622144827_AddNewsTitle.cs
> +            migrationBuilder.AddColumn<string>(
Bitte noch in der Configuration die maxlength festlegen und die migration erneut ausführen (bzw. die alte rückgängig machen)

2023-06-23 11:36 UTC, wolfgangroese commented
due to messed up migrations i started a new branch feature/arpa-910-add-title-to-news.

2023-06-23 11:36 UTC, closed without merging